app/routes.py
from flask import Blueprint, render_template, session, redirect, request, abort, flash, jsonify
from app.users.forms import StudentForm, CollegeForm, CourseForm
import app.models as models




routes = Blueprint('routes', __name__)

@routes.after_request
def after_request(response):
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    return response

@routes.route('/add_student/<college>')
def dynamic_dropdown(college):
    courses = models.Student.courses_from_college(college)

    course_list = []

    for course in courses:
        courseObj = {}
        courseObj['name'] = course
        course_list.append(courseObj)

    return jsonify({'courses': course_list})

    

@routes.route('/')
def landing_page():
    students = models.Student.all()
    return render_template("student_table.html", students=students)

@routes.route('/add_student', methods=['POST', 'GET'])
def add_student():

    form = StudentForm(request.form)

    colleges = []
    courses = []
    for item in models.College.all():
        colleges.append(item[0])

    form.college_code.choices = colleges

    for item in models.Student.courses_from_college(form.college_code.choices[0]):
        courses.append(item[0])

    form.course_code.choices = courses

    if request.method == 'POST':
        if form.profile_url.data == "":
            flash("Error: Please fill in all of the required info.")
            return render_template('add_student.html', form=form)
        if form.validate_on_submit():
            try:
                student = models.Student(studentID = form.idnum.data, name = form.name.data, college_code = form.college_code.data, \
                course_code = form.course_code.data, year = form.year_level.data, gender = form.gender.data, profile_url = form.profile_url.data)
                student.add()
                flash("Student added.")
                return redirect('/')
            except:
                flash("Duplicate Info. Please try again.")
                return render_template('add_student.html', form=form)
        else:
            flash("Please enter the correct information.")
            return render_template('add_student.html', form=form)
    else:
        return render_template('add_student.html', form=form)

@routes.route('/edit_student', methods=['POST', 'GET'])
def edit_student():

    id = request.args["student_id"]

    if request.method == 'POST':
        form = StudentForm(request.form)

        if form.validate_on_submit():
            try:
                student = models.Student(studentID = form.idnum.data, name = form.name.data, college_code = form.college_code.data, \
                course_code = form.course_code.data, year = form.year_level.data, gender = form.gender.data, profile_url = form.profile_url.data)
                student.edit(id)
                flash("Edit Successful.")
                print(session)
                return redirect('/')
            except:
                flash("Duplicate ID. Please try again.")
        else:
            flash("Please enter the correct information.")
            
    # if get 
    user_edit = models.Student.get(id)

    form = StudentForm(request.form, college_code=user_edit[3], course_code=user_edit[2])

    colleges = []
    courses = []
    for item in models.College.all():
        colleges.append(item[0])
    for item in models.Student.courses_from_college(form.college_code.data):
        courses.append(item[0])

    form.college_code.choices = colleges
    form.course_code.choices = courses
    
    formlist = [form.idnum, form.name, form.course_code, form.college_code, form.year_level, form.gender, form.profile_url]
    x = 0
    for item in formlist:
        item.data = user_edit[x]
        x += 1

    return render_template('edit_student.html', form=form)


@routes.route('/delete_student', methods=['POST', 'GET'])
def delete_student():
    id = request.args["student_id"]
    models.Student.delete(id)
    flash('Student has been successfully deleted.')
    return redirect("/")


# -- Course

@routes.route('/course_table')
def course_table():
    courses = models.Course.all()
    return render_template("course_table.html", courses=courses)

@routes.route('/add_course', methods=['POST', 'GET'])
def add_course():
    form = CourseForm(request.form)

    colleges = []
    for item in models.College.all():
        colleges.append(item[0])

    form.college_code.choices = colleges

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                course = models.Course(course_code=form.course_code.data, course_name=form.course_name.data, college_code=form.college_code.data)
                course.add()
                flash("Course added.")
                return redirect('/course_table')
            except:
                flash("Duplicate ID. Please try again.")
                return render_template('add_course.html', form=form)
        else:
            flash("Please enter the correct information.")
            return render_template('add_course.html', form=form)
    else:
        return render_template('add_course.html', form=form)

@routes.route('/edit_course', methods=['POST', 'GET'])
def edit_course():
    id = request.args["course_id"]

    if request.method == 'POST':
        form = CourseForm(request.form)

        if form.validate_on_submit():
            try:
                course = models.Course(course_code=form.course_code.data, course_name=form.course_name.data, college_code=form.college_code.data)
                course.edit(id)
                flash("Edit Successful.")
                print(session)
                return redirect('/course_table')
            except:
                flash("Duplicate ID. Please try again.")
                colleges = []

                for item in models.College.all():
                    colleges.append(item[0])

                form.college_code.choices = colleges
                return render_template('edit_course.html', form=form)
        else:
            flash("Please enter the correct information.")
            colleges = []

            for item in models.College.all():
                colleges.append(item[0])

            form.college_code.choices = colleges
            return render_template('edit_course.html', form=form)
    # if get
    else:
        
        course_edit = models.Course.get(id)

        form = CourseForm(request.form, college_code=course_edit[2])

        colleges = []

        for item in models.College.all():
            colleges.append(item[0])

        form.college_code.choices = colleges
        
        formlist = [form.course_code, form.course_name, form.college_code]
        x = 0
        for item in formlist:
            item.data = course_edit[x]
            x += 1
 
        return render_template('edit_course.html', form=form)

@routes.route('/delete_course', methods=['POST', 'GET'])
def delete_course():
    id = request.args["course_id"]
    print(id)
    models.Course.delete(id)
    flash('Course has been successfully deleted.')
    return redirect("/course_table")

# --- College Routes

@routes.route('/college_table')
def college_table():
    colleges = models.College.all()
    return render_template("college_table.html", colleges=colleges)


@routes.route('/add_college', methods=['POST', 'GET'])
def add_college():
    form = CollegeForm(request.form)

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                college = models.College(college_code=form.college_code.data, college_name=form.college_name.data)
                college.add()
                flash("College added.")
                return redirect('/college_table')
            except:
                flash("Duplicate ID. Please try again.")
                return render_template('add_college.html', form=form)
        else:
            flash("Please enter the correct information.")
            return render_template('add_college.html', form=form)
    else:
        return render_template('add_college.html', form=form)

@routes.route('/edit_college', methods=['POST', 'GET'])
def edit_college():
    id = request.args["college_id"]

    if request.method == 'POST':
        form = CollegeForm(request.form)

        if form.validate_on_submit():
            try:
                college = models.College(college_code=form.college_code.data, college_name=form.college_name.data)
                college.edit(id)
                flash("Edit Successful.")
                print(session)
                return redirect('/college_table')
            except:
                flash("Duplicate ID. Please try again.")
                return render_template('edit_college.html', form=form)
        else:
            flash("Please enter the correct information.")
            return render_template('edit_college.html', form=form)
    # if get
    else:
        
        college_edit = models.College.get(id)

        form = CollegeForm(request.form)
        
        formlist = [form.college_code, form.college_name]
        x = 0
        for item in formlist:
            item.data = college_edit[x]
            print(item.data)
            x += 1
 
        return render_template('edit_college.html', form=form)


@routes.route('/delete_college', methods=['POST', 'GET'])
def delete_college():
    id = request.args["college_id"]
    models.College.delete(id)
    flash('College has been successfully deleted.')
    return redirect("/college_table")


# --- Search Routes

@routes.route("/search", methods=['POST', 'GET'])
def search():
    print("Hi")
    # if request.method == "POST":
    print("proc")
    text = request.args['searchText']
    print(text)
    if text != '':
        students = models.Student.search(text)
    else:
        students = models.Student.all()
    print(students)
    return render_template('student_table_gen.html', students=students)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">

    <!-- Code for my own css  -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />

    {% block css %} {% endblock %}

    <title>{% block title %}Welcome{% endblock %}</title>
    
  </head>

  <body>
    <nav class="navbar fixed-top navbar-custom navbar-expand-md navbar-dark bg-secondary">
      <div class="container-fluid">
        <a href = "{{ url_for('routes.landing_page') }}" class="nav-link navbar-brand">SIS Web-App</a>

        <div class="justify-content-end align-center">
          <ul class="navbar-nav nav-pills">
            <li class="nav-item">
              <a href= "{{ url_for('routes.landing_page') }}" class="nav-link active">Student Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.course_table') }}" class="nav-link">Course Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.college_table') }}" class="nav-link">College Table</a>
            </li>
            <li class="nav-item">
              <span class="mx-3"></span>
            </li>
            <li class="nav-item">
              <button class="btn btn-dark"
              onclick="window.location.href='{{ url_for( 'routes.add_student' ) }}';"
              >Add Student</button>
            </li>
          </ul>
        </div>

      </div>
    </nav>
    <section>
      <div class="row m-0 p-0">
        <div class="col" style="height: 51px;"></div>
    </div>
    {% with messages = get_flashed_messages() %}  
        {% if messages %}
            <div class="alert alert-warning alert-dismissible fade fade-out-down show" role="alert">
                {% for message in messages %}  
                        <p>{{ message }}</p>  
                {% endfor %}  
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}  
    {% endwith %} 
    {% block content %} {% endblock %}
    </section>
    
    

    <!-- <script 
      src="https://code.jquery.com/jquery-3.6.3.slim.js" 
      integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc=" 
      crossorigin="anonymous"
    ></script> -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    {% block scripts %} {% endblock %}

  </body>
</html>

app/templates/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">

    <!-- Code for my own css  -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />

    {% block css %} {% endblock %}

    <title>{% block title %}Welcome{% endblock %}</title>
    
  </head>

  <body>
    <nav class="navbar fixed-top navbar-custom navbar-expand-md navbar-dark bg-secondary">
      <div class="container-fluid">
        <a href = "{{ url_for('routes.landing_page') }}" class="nav-link navbar-brand">SIS Web-App</a>

        <div class="justify-content-end align-center">
          <ul class="navbar-nav nav-pills">
            <li class="nav-item">
              <a href= "{{ url_for('routes.landing_page') }}" class="nav-link">Student Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.course_table') }}" class="nav-link active">Course Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.college_table') }}" class="nav-link">College Table</a>
            </li>
            <li class="nav-item">
              <span class="mx-3"></span>
            </li>
            <li class="nav-item">
              <button class="btn btn-dark"
              onclick="window.location.href='{{ url_for( 'routes.add_student' ) }}';"
              >Add Student</button>
            </li>
          </ul>
        </div>

      </div>
    </nav>
    <section>
      <div class="row m-0 p-0">
        <div class="col" style="height: 51px;"></div>
    </div>
    {% with messages = get_flashed_messages() %}  
        {% if messages %}
            <div class="alert alert-warning alert-dismissible fade fade-out-down show" role="alert">
                {% for message in messages %}  
                        <p>{{ message }}</p>  
                {% endfor %}  
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}  
    {% endwith %} 
    {% block content %} {% endblock %}
    </section>
    
    

    <!-- <script 
      src="https://code.jquery.com/jquery-3.6.3.slim.js" 
      integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc=" 
      crossorigin="anonymous"
    ></script> -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    {% block scripts %} {% endblock %}

  </body>
</html>

app/templates/base2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">

    <!-- Code for my own css  -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />

    {% block css %} {% endblock %}

    <title>{% block title %}Welcome{% endblock %}</title>
    
  </head>

  <body>
    <nav class="navbar fixed-top navbar-custom navbar-expand-md navbar-dark bg-secondary">
      <div class="container-fluid">
        <a href = "{{ url_for('routes.landing_page') }}" class="nav-link navbar-brand">SIS Web-App</a>

        <div class="justify-content-end align-center">
          <ul class="navbar-nav nav-pills">
            <li class="nav-item">
              <a href= "{{ url_for('routes.landing_page') }}" class="nav-link">Student Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.course_table') }}" class="nav-link">Course Table</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('routes.college_table') }}" class="nav-link active">College Table</a>
            </li>
            <li class="nav-item">
              <span class="mx-3"></span>
            </li>
            <li class="nav-item">
              <button class="btn btn-dark"
              onclick="window.location.href='{{ url_for( 'routes.add_student' ) }}';"
              >Add Student</button>
            </li>
          </ul>
        </div>

      </div>
    </nav>
    <section>
      <div class="row m-0 p-0">
        <div class="col" style="height: 51px;"></div>
    </div>
    {% with messages = get_flashed_messages() %}  
        {% if messages %}
            <div class="alert alert-warning alert-dismissible fade fade-out-down show" role="alert">
                {% for message in messages %}  
                        <p>{{ message }}</p>  
                {% endfor %}  
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}  
    {% endwith %} 
    {% block content %} {% endblock %}
    </section>
    
    

    <!-- <script 
      src="https://code.jquery.com/jquery-3.6.3.slim.js" 
      integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc=" 
      crossorigin="anonymous"
    ></script> -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    {% block scripts %} {% endblock %}

  </body>
</html>

app/templates/college_table.html
{% extends "base2.html" %} 
{% block css %} 
<link rel="stylesheet" href="{{ url_for('static', filename='css/college_table.css') }}" />
{% endblock %}
{% block title %}College Table{% endblock %} 
{% block content %}

<div class="container mt-5">
    <div class="row">
        <button type="submit"
        class="btn btn-dark w-25"
        onclick="window.location.href='{{ url_for( 'routes.add_college') }}';"
        >
            Add College
        </button>
        <span class="spacer"></span>
        <div class="input-group w-50">
            <button class="btn btn-outline-secondary" type="button" id="button-addon1">Search</button>
            <input type="text" class="form-control" onkeyup="liveSearch(this.value)" placeholder="Name or ID" aria-label="Example text with button addon" aria-describedby="button-addon1">
        </div>
    </div>
</div>

<div class="container container-config">
    <div class="container">
        <h2>College List</h2>
        
        <div id="college_table_test">
            {% for college in colleges %}
            <div class="custom-card card mt-3 py-3">
                <div class="row">
                    <div class="col-2">
                        <div class="card-body border-end border-dark border-1">
                            <h5 class="mb-0">{{college[0]}}</h5>      
                        </div>
                    </div>
                    <div class="col-7">
                        <div class="card-body border-end border-dark border-1">
                            <h5>{{college[1]}}</h5>
                        </div>
                    </div>
                    <div class="col-1 d-flex justify-content-center align-items-center">
                        <a class="btn btn-primary change-width" href="{{ url_for("routes.edit_college", college_id=college[0]) }}">Edit</a>
                    </div>
                    <div class="col-auto d-flex justify-content-center align-items-center">
                        <a class="btn btn-danger" href="{{ url_for("routes.delete_college", college_id=college[0]) }}">Delete</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

{% block scripts %} 
<script>
    
    function liveSearch(value){
        

        $.ajax({
            url:"{{ url_for("routes.search_college") }}",
            data:{searchText: value},
            
            type:"GET",

            success: function(data){
                console.log(data)
                $('#college_table_test').html(data);
            }
        });
    }
    $('#searchinput').keyup(function(){
        var search = $(this).val();
        load_data(search);
    });

</script>
{% endblock %}

app/templates/college_table_gen.html
{% for college in colleges %}
<div class="custom-card card mt-3 py-3">
    <div class="row">
        <div class="col-2">
            <div class="card-body border-end border-dark border-1">
                <h5 class="mb-0">{{college[0]}}</h5>      
            </div>
        </div>
        <div class="col-7">
            <div class="card-body border-end border-dark border-1">
                <h5>{{college[1]}}</h5>
            </div>
        </div>
        <div class="col-1 d-flex justify-content-center align-items-center">
            <a class="btn btn-primary change-width" href="{{ url_for("routes.edit_college", college_id=college[0]) }}">Edit</a>
        </div>
        <div class="col-auto d-flex justify-content-center align-items-center">
            <a class="btn btn-danger" href="{{ url_for("routes.delete_college", college_id=college[0]) }}">Delete</a>
        </div>
    </div>
</div>
{% endfor %}

app/templates/course_table.html
{% extends "base1.html" %} 
{% block css %} 
<link rel="stylesheet" href="{{ url_for('static', filename='css/course_table.css') }}" />
{% endblock %}
{% block title %}Course Table{% endblock %} 
{% block content %}

<div class="container mt-5">
    <div class="row">
        <button type="submit"
        class="btn btn-dark w-25"
        onclick="window.location.href='{{ url_for( 'routes.add_course') }}';"
        >
            Add Course
        </button>
        <span class="spacer"></span>
        <div class="input-group w-50">
            <button class="btn btn-outline-secondary" type="button" id="button-addon1">Search</button>
            <input type="text" class="form-control" onkeyup="liveSearch(this.value)" placeholder="Name or ID" aria-label="Example text with button addon" aria-describedby="button-addon1">
        </div>
    </div>
</div>

<div class="container container-config">
    <div class="container">
        <h2>Course List</h2>
        
        <div id="course_table_test">
            {% for course in courses %}
            <div class="custom-card card mt-3 py-3">
                <div class="row">
                    <div class="col-2">
                        <div class="card-body border-end border-dark border-1">
                            <h5 class="mb-0">{{course[2]}}</h5>      
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="card-body border-end border-dark border-1">
                            <h5 class="mb-0">{{course[0]}}</h5>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="card-body border-end border-dark border-1">
                            <h6>{{course[1]}}</h6>
                        </div>
                    </div>
                    <div class="col-1 d-flex justify-content-center align-items-center">
                        <a class="btn btn-primary change-width" href="{{ url_for("routes.edit_course", course_id=course[0]) }}">Edit</a>
                    </div>
                    <div class="col-auto d-flex justify-content-center align-items-center">
                        <a class="btn btn-danger" href="{{ url_for("routes.delete_course", course_id=course[0]) }}">Delete</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

{% block scripts %} 
<script>
    
    function liveSearch(value){
        

        $.ajax({
            url:"{{ url_for("routes.search_course") }}",
            data:{searchText: value},
            
            type:"GET",

            success: function(data){
                console.log(data)
                $('#course_table_test').html(data);
            }
        });
    }
    $('#searchinput').keyup(function(){
        var search = $(this).val();
        load_data(search);
    });

</script>
{% endblock %}

app/templates/student_table.html
{% extends "base.html" %} 
{% block css %} {% endblock %}
{% block title %}Student Table{% endblock %} 
{% block content %}

<div class="container mt-5">
    <div class="row">
        <button type="submit"
        class="btn btn-dark w-25"
        onclick="window.location.href='{{ url_for( 'routes.add_student') }}';"
        >
            Add Student
        </button>
        <span class="spacer"></span>
        <div class="input-group w-50">
            <button class="btn btn-outline-secondary" type="button" id="button-addon1">Search</button>
            <input type="text" class="form-control" onkeyup="liveSearch(this.value)" placeholder="Name or ID" aria-label="Example text with button addon" aria-describedby="button-addon1">
        </div>
    </div>
</div>

<div class="container container-config">
    <div class="container">
        <h2>Student List</h2>
        
        <div id="student_table_test">
            {% for student in students %}
            <div class="custom-card card mt-3 py-3">
                <div class="row">
                    <div class="col-3 border-end border-dark border-1">
                        
                        <div class="container px-0 d-flex justify-content-center">
                            <img src= {{student[6]}} class="profile-pic rounded-circle shadow-lg mb-3">
                        </div>
                        <div class="container px-0 d-flex justify-content-center">
                            <h2 class="mb-0">{{student[0]}}</h2>
                        </div>
                        
                    </div>
                    <div class="col-6 ms-5">
                        <div class="card-body border-end border-dark border-1">
                            <h1 class="pb-4">{{student[1]}} <span><h6>{{student[5]}}</h6></span></h1>
                            
                            <h5>{{student[2]}}</h5>
                            <h6>{{student[3]}} {{student[4]}}</h6>
                        </div>
                    </div>
                    <div class="col-1 d-flex justify-content-center align-items-center">
                        <a class="btn btn-primary change-width" href="{{ url_for("routes.edit_student", student_id=student[0]) }}">Edit</a>
                    </div>
                    <div class="col-auto d-flex justify-content-center align-items-center">
                        <a class="btn btn-danger" href="{{ url_for("routes.delete_student", student_id=student[0]) }}">Delete</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

{% block scripts %} 
<script>
    
    function liveSearch(value){
        

        $.ajax({
            url:"{{ url_for("routes.search") }}",
            data:{searchText: value},
            
            type:"GET",

            success: function(data){
                console.log(data)
                $('#student_table_test').html(data);
            }
        });
    }
    $('#searchinput').keyup(function(){
        var search = $(this).val();
        load_data(search);
    });

</script>
{% endblock %}